### ISSUE TITLE
User feedback on a website, missing information

### ISSUE THREAD

**Issue by slrslr** [bitdust-io/www#107]
Page https://bitdust.io/ below "The product (alpha)" shows the short description of the product but it and also https://bitdust.io/wiki/sharing.html does not explain if i can share the file with anyone on the network and others can find it easily.

Also on that page i am missing the information if it is using some cryptocurrency/blockchain which needs a POW to confirm.

Third think regarding anonymity, possibly i would like to know how that anonymity works, i think there is no link to such a detail or it does not explain it right on that main page.

**Comment by vesellov** [comment]
Hi @slrslr !  I just updated that page with additional paragraph and tried to describe it a bit more for you. : https://bitdust.io/wiki/sharing.html#customer-data-flow-step-by-step

No... BitDust is not using any blockchain yet. I did some experiments with Bismuth though...

It seems the most related topic about anonymity is possible the "user identification": https://bitdust.io/wiki/identities.html
... but probably missing some details about that subject, I agree... will try to make it more clear and come back to you, @slrslr .

Thank you for great and valid feedback! please continue :+1:

**Comment by vesellov** [comment]
Added also a new paragraph about anonymity on the "identification" page.  Can you please also check? : https://bitdust.io/wiki/identities.html#your-privacy 
hope it answers you questions, @slrslr ! :+1:
