### ISSUE TITLE
Q1 - Typo

### ISSUE THREAD

**Issue by KevinArellano94** [bitdust-io/www#126]
Not sure if a typo or I'm not understanding it well. On the main site there are 4 Quarter icon, where it starts with Q4 => Q1 => Q1 => Q3. Could be a different interpretation on my part. Let me know if so i can PR it and update it for you.

https://bitdust.io/#roadmap

**Comment by vesellov** [comment]
Ya... originally, when we built the web-site, we had a team of 5 people working together one day per week on the project. So the plan was to launch a BitDust blockchain in the second half of the 2022. Unfortunately things are changing and we are not working together that much anymore. Currently I am on the second step in the roadmap and did some parts of the blockchain implementation already.

The Q1 label stands for: first quarter of the 2021... 

I propose to just remove those Q labels from the roadmap and shift items in the roadmap one year ahead : just to make it more correct...  and do not look so much pessimistic. :smile: 

Please go ahead and prepare the change, @KevinArellano94 
Very appreciate!

**Comment by KevinArellano94** [comment]
Good morning!  Yup no worries man, I have the changes ready to do a PR.  Do you want to create a new branch or how would you like me to provide you with the changes?

I'm getting this error which probably due to account security:
  remote: Permission to bitdust-io/www.git denied to KevinArellano94.
  fatal: unable to access 'https://github.com/bitdust-io/www.git/': The requested URL returned error: 403

**Comment by vesellov** [comment]
Thank you, @KevinArellano94 !

Not sure why it complained about the permissions... With git you normally do not push your code via https, only via ssh+git method. This you chose when are going to clone the repo for the first time. 

Sometimes I am using https in my remote upstream instead, just to avoid mistakes with git locally and accidentally push to the main master branch directly. Normally, every code-change to the main repo I do via pull request.

And you can just use you master branch when you do any contribution to BitDust. Usually, I use only the master branch in all of the repos.

There is a script running on the server which automatically update the bitdust.io website from this repo. So the changes suppose to be live in few minutes. :handshake:

**Comment by KevinArellano94** [comment]
Went ahead and added the Quarter icon back but kept the text removed.  Pushed to master.  Let me know what you think.

**Comment by vesellov** [comment]
Looks good :+1:
